nahuellorenzo/recalc

package.json, test/core.test.js
Añado test para la comprobación de los resultados que arroja la función "div" mediante las siguientes cuentas, solicitando que los mismos sean agregados a la rama "dev":
- 2 / 2 = 1
- 12 / 0 = Math Error
=> Agrega test para la funcion div

package.json, test/core.test.js
Añado test para la comprobación de los resultados que arroja la función "mul" mediante las siguientes cuentas, solicitando que los mismos sean agregados a la rama "dev":
3 * 3 = 9
8 * (-6) = -48
=> Agrega test para la funcion mul

src/controllers.js
Añado endpoint en la API realizando el controller para GET /div/:a/:b que se relaciona con la funcion div del archivo core.js
=> Agrega el endpoint en la API para el metodo GET /div/:a/:b

src/controllers.js
Añado endpoint en la API realizando el controller para GET /pow/:a que se relaciona con la funcion pow del archivo core.js
=> Agrega el endpoint en la API para el metodo GET /pow/:a

src/controllers.js
Añado endpoint en la API realizando el controller para GET /mul/:a/:b que se relaciona con la función mul del archivo core.js
=> Agrega el endpoint en la API para el metodo GET /mul/:a/:b

test/core.test.js
Añado test para la comprobación de que el resultado es un numero negativo cuando el segundo parametro es mayor que el primero para la función "sub" mediante la siguiente cuenta, solicitando que el mismo sea agregado a la rama "dev":
6 - 8 = -2
=> Agrega test para la funcion sub que da resultado negativo

src/controllers.js
Arreglo bug de controller de SUB que hacia que no se guarde el segundo parámetro en la tabla History.
=> Arreglo bug de controller SUB

test/models.test.js
Agrego test para comprobar que se guardan todos los parámetros de la resta en el history tanto para números positivos como negativos.
=> Agrego test para comprobar que se guardan todos los parametros

src/controllers.js, src/models.js
Agrego atributo error en el modelo history para guardar información de cualquier error que se produzca en una operación y lo pongo en los parámetros del createHistory en null para que cualquiera pueda cambiar el null por un string y mande el error.
=> Agrego atributo error al modelo history

test/models.test.js
-Agrego test para comprobar que el atributo error se guarda en el history.
-Arreglo el valor del resultado del segundo test ya que (-2) - (-2) = 0
=> Agrego test para el atributo error y para arreglar valor del resultado del segundo test

src/controllers.js
Agrego la función find all que obtiene el historial de operaciones realizadas.
=> Agrego función para obtener todo el historial

src/controllers.js, src/models.js
Cambio la implementación de la función para obtener el historial y muevo parte del código al archivo controllers.js
=> Cambio la implementacion de la funcion para llevarla a otro archivo

src/controllers.js, src/models.js
Agrego función deleteAllHistory en models.js para eliminar todos los registros de la tabla History e implemento esta función en el endpoint /allDeleted donde te dice cuantos registros se eliminaron en caso de que los haya en la base de datos.
=> Agrego función para borrar todos los registros de History

test/models.test.js
Agrego test para verificar que la función implementada para obtener el historial de operaciones, funcione de manera correcta, trayendo de la base de datos todas las operaciones realizadas
=> Agrego test para verificar que se recupere bien el historial desde la BD

src/controllers.js
Agrego función para guardar el historial de operaciones en la BD para el endpoint add.
=> Agrego función para guardar el historial en la BD

src/controllers.js
Modifico el endpoint GET /mul/:a/:b para que guarde la entrada del historial en la base de datos a través del modelo usando la función createHistoryEntry.
=> Modifico el endpoint de MUL para que guarde la entrada en la BD

test/api.test.js
Arreglo el código de API substract para que pueda correr el test correctamente
=> Soluciono error con el test de substract

src/controllers.js
Agrego la opción de createHistory para la operación Pow
=> Agrego createHistory para pow

test/api.test.js
Agrego test para verificar que la endpoit de power retorne un error 400 cuando el parametro ingresado no es un numero.
=> Agrego test para endpoint de power

test/api.test.js
Agrego test para verificar que el endpoint de suma (add) devuelve un status 200 cuando el segundo parámetro es negativo y resultado es menor al primer parámetro.
=> Agrego test para endpoint de add

test/api.test.js
Agrego test para verificar que el endpoint de multiplicación devuelve un status 200 cuando ambos parámetros son decimales y verificar que el resultado sea con decimales.
=> Agrego test para el endpoint de multiplicacion

src/controllers.js, src/models.js
Agrego función relacionada con la base de datos para poder obtener una entrada del historial por ID. Y el endpoint para obtener una entrada del historial por id.
=> Agrego feature id controller

src/cli.js, src/controllers.js, src/core.js, src/seed.js
Modifico los archivos necesarios para poder utilizar la función sqrt en la aplicación y persistiendo las operaciones realizadas en la BD
=> Agrego sqrt como opción en las operaciones de la aplicación

test/api.test.js
Agrego test para comprobar que 0.1 + 0.2 = 0.3, verificando que funcione bien el endpoint de Suma
=> Agrego test para comprobar una suma

src/controllers.js
Modifico el endpoint GET /div/:a/:b para que guarde la entrada del historial en la base de datos a través del modelo usando la función createHistoryEntry.
=> Modifico el endpoint de div para que guarde la entrada en la BD

src/controllers.js, test/api.test.js
Agrego test para verificar que el endpoint de division devuelve un status 400 cuando el segundo parametro es un cero.
Modifico el controller para la division para arrojar un status 400 cuando el segundo parametro es cero.
=> Agrego test y Modifico el endpoint para la division

test/api.test.js
Agrego test para verificar que el endpoint de raiz cuadrada que devuelve un status 200 cuando el parametro es un numero y verificar que el resultado sea 10, cuando el parametro es 100.
=> Agrego test para el endpoint sqrt

test/api.test.js
Agrego test para verficar que el endpoint de deletedAll retorna la cantidad de registros eliminados correctamente y con status 200
=> Agrego test para comprobar el endPoint de deletedAll

test/api.test.js
Agrego test para verificar que el endpoint de all retorne el history completo con status 200
=> Agrego test para testear endPoint de All

test/api.test.js, test/core.test.js
Agrego test para la función que convierte los números decimales a binarios
=> Agrego test para la funcion binary

src/controllers.js, src/models.js, test/api.test.js
Agrego filtro por operaciones opcional en el endpoint all para que pueda traer todos los registros de la bd y también que pueda traer por ejemplo solo los registros de mul con el endpoint all/mul. De esta manera funciona con todas las operaciones.
=> Agrego feature de filtros por operaciones

src/public/index.js, test/ui.test.js
Resuelvo la multiplicación en la interfaz debido a que los botones existían pero no estaba hecha la conexión con la API.
Realizo el test e2e correspondiente.
=> Agrego función MUL en la interfaz y su respectivo test e2e

src/public/index.html, src/public/index.js, test/ui.test.js
Agrego a la interfaz gráfica la posibilidad de hacer la potencia, agregando el error cuando el número es demasiado grande y el test correspondiente a la potencia
=> Agrego operación de Pow

src/public/index.js, test/ui.test.js
Resuelvo la división en la interfaz debido a que los botones existían pero no estaba hecha la conexión con la API y si el divisor es 0 muestro un mensaje de error en el display. Realizo el test e2e correspondiente.
=> Agrego funcion Div en la interfaz y su respectivo test e2e

.eslintrc.cjs, src/api.js, src/controllers.js, src/core.js, src/models.js, src/public/index.js
Realizamos las modificaciones para solucionar los errores que arrojaban los test estáticos
=> Test estáticos

src/public/index.js, test/ui.test.js
Arreglo el bug del botón C que hacia que cuando se lo clickeaba aparezca c en el display, ahora aparece 0 y cumple su función de reestablecer la operación que se ingreso. Además se agrego su test correspondiente.
=> Bug boton c

src/public/index.html, src/public/index.js, test/ui.test.js
Agrego la funcionalidad de square a la interfez gráfica de la calculadora, realizando además su test e2e correspondiente
=> Agrego funcionalidad square y test

src/public/index.js, test/ui.test.js
Arreglo el bug que mostraba undefined cada vez que se ingresaba un numero sin operación, se clickeaba "=" y mostraba en el display undefined. Además agrego el test e2e correspondiente.
=> Bug undefined "="

test/ui.test.js
Agrego el test correspondiente al error que se muestra en pantalla cuando se quiere realizar una potencia con un numero mayor a 100000
=> Agrego test e2e para verificar el error de POW cuando se quiere trabajar con un numero mayor a 100000

test/ui.test.js
Agrego el test correspondiente al error que se muestra en pantalla cuando se quiere realizar una división por cero.
=> Agrego test e2e para verificar el error de div cuando se quiere dividir por cero
